alliancedigital/src/Entity/Calendar.php
<?php

namespace App\Entity;

use App\Repository\CalendarRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CalendarRepository::class)]
class Calendar
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $title = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $start = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $end = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?bool $all_day = null;

    #[ORM\Column(length: 7)]
    private ?string $background_color = null;

    #[ORM\Column(length: 7)]
    private ?string $border_color = null;

    #[ORM\Column(length: 7)]
    private ?string $text_color = null;

    #[ORM\Column]
    private ?bool $fait = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $par = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(\DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function isAllDay(): ?bool
    {
        return $this->all_day;
    }

    public function setAllDay(bool $all_day): self
    {
        $this->all_day = $all_day;

        return $this;
    }

    public function getBackgroundColor(): ?string
    {
        return $this->background_color;
    }

    public function setBackgroundColor(string $background_color): self
    {
        $this->background_color = $background_color;

        return $this;
    }

    public function getBorderColor(): ?string
    {
        return $this->border_color;
    }

    public function setBorderColor(string $border_color): self
    {
        $this->border_color = $border_color;

        return $this;
    }

    public function getTextColor(): ?string
    {
        return $this->text_color;
    }

    public function setTextColor(string $text_color): self
    {
        $this->text_color = $text_color;

        return $this;
    }

    public function isFait(): ?bool
    {
        return $this->fait;
    }

    public function setFait(bool $fait): self
    {
        $this->fait = $fait;

        return $this;
    }

    public function getPar(): ?string
    {
        return $this->par;
    }

    public function setPar(?string $par): self
    {
        $this->par = $par;

        return $this;
    }
}

alliancedigital/src/Form/CalendarType.php
<?php

namespace App\Form;

use App\Entity\Calendar;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\ColorType;


class CalendarType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('start', DateTimeType::class,[
                'date_widget' => 'single_text'
            ])
            ->add('end', DateTimeType::class,[
                'date_widget' => 'single_text'
            ])
            ->add('description')
            ->add('all_day')
            ->add('fait')
            ->add('par')
            ->add('background_color', ColorType::class)
            ->add('border_color', ColorType::class)
            ->add('text_color', ColorType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Calendar::class,
        ]);
    }
}

alliancedigital/src/Controller/CalendarController.php
<?php

namespace App\Controller;

use App\Entity\Calendar;
use App\Form\CalendarType;
use App\Repository\CalendarRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;



#[Route('/calendar')]
class CalendarController extends AbstractController
{
    #[Route('/', name: 'app_calendar_index', methods: ['GET'])]
    public function index(CalendarRepository $calendarRepository): Response
    {
        return $this->render('calendar/index.html.twig', [
            'calendars' => $calendarRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_calendar_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CalendarRepository $calendarRepository): Response
    {
        $calendar = new Calendar();
        $form = $this->createForm(CalendarType::class, $calendar);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $calendarRepository->save($calendar, true);

            return $this->redirectToRoute('app_calendar_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('calendar/new.html.twig', [
            'calendar' => $calendar,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_calendar_show', methods: ['GET'])]
    public function show(Calendar $calendar): Response
    {
        return $this->render('calendar/show.html.twig', [
            'calendar' => $calendar,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_calendar_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Calendar $calendar, ManagerRegistry $managerRegistry): Response
    {
        $form = $this->createFormBuilder($calendar)
            ->add('fait', CheckboxType::class, [
                'required' => false,
            ])
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $managerRegistry->getManager();
            $entityManager->flush();

            return $this->redirectToRoute('app_home');
        }

        return $this->render('calendar/edit.html.twig', [
            'calendar' => $calendar,
            'form' => $form->createView(),
        ]);
    }



    #[Route('/{id}', name: 'app_calendar_delete', methods: ['POST'])]
    public function delete(Request $request, Calendar $calendar, CalendarRepository $calendarRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$calendar->getId(), $request->request->get('_token'))) {
            $calendarRepository->remove($calendar, true);
        }

        return $this->redirectToRoute('app_calendar_index', [], Response::HTTP_SEE_OTHER);
    }
}

alliancedigital/templates/calendar/_delete_form.html.twig
<form method="post" action="{{ path('app_calendar_delete', {'id': calendar.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ calendar.id) }}">
    <button class="btn">Delete</button>
</form>

alliancedigital/templates/calendar/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

alliancedigital/templates/calendar/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un événement{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        body {
            background-color: #333333;
        }
        .card {
            margin-top: 50px;
            background-color: #FFFFFF;
            max-width: 800px; /* set a maximum width for the card */
            margin-left: auto; /* center the card horizontally */
            margin-right: auto;
        }
        .card-header a {
            color: #E95B0C;
        }
        .btn{
            background-color: #E95B0C;
            color : #FFFFFF;
        }
        .btn:hover{
            background-color: #E95B0C;
            color : #FFFFFF;
        }
        .btn{
            display: block;
            margin: 0 auto;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="container">
        <nav class="navbar navbar-expand-lg" style="background-color: #333333;">
            <a class="navbar-brand" href="{{ path('app_home') }}">
                <button type="button" class="btn btn-lg" style="background-color: #EA5B0C; color: #FFFFFF;">Accueil</button>
            </a>
        </nav>

        <div class="card">
            <div class="card-header" style="background-color: #E95B0C;">
                <h1 style="color: #FFFFFF;">Modifier un événement</h1>
            </div>
            <div class="card-body">
                {{ form_start(form) }}
                {{ form_errors(form) }}

                {{ form_label(form.fait) }}
                {{ form_widget(form.fait, { 'attr': {'class':  'fait'} }) }}

                <button type="submit" class="btn">Enregistrer</button>

                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

alliancedigital/templates/calendar/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Calendar index{% endblock %}

{% block body %}
    <h1>Calendar index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Start</th>
                <th>End</th>
                <th>Description</th>
                <th>All_day</th>
                <th>Background_color</th>
                <th>Border_color</th>
                <th>Text_color</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for calendar in calendars %}
            <tr>
                <td>{{ calendar.id }}</td>
                <td>{{ calendar.title }}</td>
                <td>{{ calendar.start ? calendar.start|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ calendar.end ? calendar.end|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ calendar.description }}</td>
                <td>{{ calendar.allDay ? 'Yes' : 'No' }}</td>
                <td>{{ calendar.backgroundColor }}</td>
                <td>{{ calendar.borderColor }}</td>
                <td>{{ calendar.textColor }}</td>
                <td>
                    <a href="{{ path('app_calendar_show', {'id': calendar.id}) }}">show</a>
                    <a href="{{ path('app_calendar_edit', {'id': calendar.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_calendar_new') }}">Create new</a>
{% endblock %}

alliancedigital/templates/calendar/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Calendar{% endblock %}

{% block body %}
    <h1>Create new Calendar</h1>

    {{ include('calendar/_form.html.twig') }}

    <a href="{{ path('app_calendar_index') }}">back to list</a>
{% endblock %}

alliancedigital/templates/calendar/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Calendar{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        body {
            background-color: #333333;
        }
        .card {
            margin-top: 50px;
            background-color: #FFFFFF;
            max-width: 800px; /* set a maximum width for the card */
            margin-left: auto; /* center the card horizontally */
            margin-right: auto;
        }
        .card-header a {
            color: #E95B0C;
        }
        .btn{
            background-color: #E95B0C;
            color : #FFFFFF;
        }
        .btn:hover{
            background-color: #E95B0C;
            color : #FFFFFF;
        }
        .btn{
            display: block;
            margin: 0 auto;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="container">
        <nav class="navbar navbar-expand-lg" style="background-color: #333333;">
            <a class="navbar-brand" href="{{ path('app_home') }}">
                <button type="button" class="btn btn-lg" style="background-color: #EA5B0C; color: #FFFFFF;">Accueil</button>
            </a>
        </nav>

        <div class="card">
            <div class="card-header" style="background-color: #E95B0C;">
                <h1 style="color: #FFFFFF;">{{ calendar.title }}</h1>
            </div>
            <div class="card-body">
                <table class="table">
                    <tbody>
                        <tr>
                            <th>Date de début</th>
                            <td>{{ calendar.start ? calendar.start|date('Y-m-d H:i:s') : '' }}</td>
                        </tr>
                        <tr>
                            <th>Date de fin</th>
                            <td>{{ calendar.end ? calendar.end|date('Y-m-d H:i:s') : '' }}</td>
                        </tr>
                        <tr>
                            <th>Description</th>
                            <td>{{ calendar.description }}</td>
                        </tr>
                    </tbody>
                </table>
                <button type="button" class="btn" id="btn-task-done">Tâche effectuée</button>
            </div>
        </div>
    </div>
{% endblock %}

alliancedigital/templates/calendar/update.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier tâche{% endblock %}

{% block body %}
    <div class="container">
        <nav class="navbar navbar-expand-lg" style="background-color: #333333;">
            <a class="navbar-brand" href="{{ path('app_home') }}">
                <button type="button" class="btn btn-lg" style="background-color: #EA5B0C; color: #FFFFFF;">Accueil</button>
            </a>
        </nav>

        <div class="card">
            <div class="card-header" style="background-color: #E95B0C;">
                <h1 style="color: #FFFFFF;">Modifier tâche</h1>
            </div>
            <div class="card-body">
                <form id="update-form">
                    <div class="form-group">
                        <label for="description">Description</label>
                        <textarea class="form-control" id="description" rows="3" required>{{ calendar.description }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="start">Date de début</label>
                        <input type="datetime-local" class="form-control" id="start" value="{{ calendar.start ? calendar.start|date('Y-m-d\TH:i:s') : '' }}" required>
                    </div>
                    <div class="form-group">
                        <label for="end">Date de fin</label>
                        <input type="datetime-local" class="form-control" id="end" value="{{ calendar.end ? calendar.end|date('Y-m-d\TH:i:s') : '' }}" required>
                    </div>
                    <button type="submit" class="btn" id="btn-update">Modifier</button>
                </form>
            </div>
        </div>
    </div>

    <script>
        const updateForm = document.getElementById('update-form');
        const btnUpdate = document.getElementById('btn-update');
        btnUpdate.addEventListener('click', async (event) => {
            event.preventDefault();
            const response = await fetch('{{ path('update_calendar', {id: calendar.id}) }}', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    description: document.getElementById('description').value,
                    start: document.getElementById('start').value,
                    end: document.getElementById('end').value
                })
            });

            if (response.ok) {
                // Mise à jour réussie, rediriger vers la page de la tâche
                window.location.href = '{{ path('calendar_show', {id: calendar.id}) }}';
            } else {
                // Gérer les erreurs
                console.error('Impossible de modifier la tâche.');
            }
        });
    </script>
{% endblock %}